IrreducibleOSS/binius

CODEOWNERS
=> [security]: Codeowners add

scripts/nightly_benchmarks.py
This adds the script to benchmark various of our examples, default sampling is set to 5 to reduce total time to benchmark.
=> [scripts] Added benchmarking script

Cargo.toml, crates/core/Cargo.toml, crates/core/src/constraint_system/channel.rs, crates/core/src/constraint_system/mod.rs, crates/core/src/lib.rs, crates/core/src/oracle/constraint.rs, crates/core/src/oracle/multilinear.rs, crates/core/src/polynomial/multivariate.rs, crates/core/src/protocols/sumcheck/prove/zerocheck.rs, crates/core/src/transparent/constant.rs, crates/core/src/transparent/mod.rs, crates/core/src/transparent/multilinear_extension.rs, crates/core/src/transparent/powers.rs, crates/core/src/transparent/select_row.rs, crates/core/src/transparent/serialization.rs, crates/core/src/transparent/step_down.rs, crates/core/src/transparent/step_up.rs, crates/core/src/transparent/tower_basis.rs, crates/field/src/packed.rs, crates/field/src/packed_extension_ops.rs, crates/field/src/serialization/canonical.rs, crates/field/src/serialization/error.rs, crates/macros/src/lib.rs, crates/math/Cargo.toml, crates/math/src/arith_expr.rs
This extends #7, providing serialization for ConstraintSystem over any tower field, and deserialization for BinaryField128b
=> [serialization] impl SerializeCanonical, DeserializeCanonical for ConstraintSystem

crates/circuits/src/plain_lookup.rs
Simplify "plain lookup" by using custom-selector flushing
=> update using selector flushing

crates/circuits/src/blake3.rs, crates/circuits/src/lib.rs, crates/circuits/src/sha256.rs, crates/circuits/src/unconstrained.rs
This PR introduces gadgets required to prove computation of Blake3 [G](https://github.com/BLAKE3-team/BLAKE3/blob/master/reference_impl/reference_impl.rs#L42) function from its reference implementation.
=> feat: Blake3 G function gadget

scripts/nightly_benchmarks.py
Updated script to run both single and multi threaded examples
=> [scripts] Add single and multi threaded runs

crates/core/src/piop/prove.rs
Attempt to fix #51
- Should the 2nd copy phase (with n_packed_vars < P::log_width) also be parallelized ? (less important because it only copies small polynomials)
- There is a duplicated function `merge_multilins` [here](https://github.com/IrreducibleOSS/binius/blob/72ba99e63dfeb29227309e4c89d72b6d0ef6a5c5/crates/core/benches/poly_commit.rs#L27C4-L27C19) , is it intended ?
- Additional remark: The 2nd copy phase is never entered during tests
=> [piop] Parallelize data copying when merging multilinears

crates/math/src/arith_expr.rs, crates/math/src/error.rs
Split out from https://github.com/IrreducibleOSS/binius/pull/55
=> [arith_expr] Add LinearNormalForm

crates/m3/src/builder/constraint_system.rs, crates/m3/src/builder/table.rs, crates/m3/src/builder/witness.rs
Based on https://github.com/IrreducibleOSS/binius/pull/73
=> [m3] Use SparseIndex for Table partitions

crates/field/benches/binary_field.rs, crates/field/benches/packed_field_iter.rs, crates/field/benches/packed_field_subfield_ops.rs, crates/field/benches/packed_field_utils.rs
Small MR to add unique names for microbenchmarks and lower measurement time to help with nightly benchmarks
=> [benches] Add unique names for micro benchmarks

crates/core/src/constraint_system/verify.rs, crates/core/src/protocols/gkr_exp/batch_verify.rs, crates/core/src/protocols/sumcheck/prove/univariate.rs, crates/core/src/protocols/sumcheck/zerocheck.rs, crates/core/src/transparent/eq_ind.rs
There was a TODO that I was going to open as a good first issue... but I didn't like the docstring so I just did the change.
=> [transparent] Improve EqIndPartialEval constructor signature

.github/workflows/benchmark.yml
Closes #CRY-163
Closes #CRY-164
Closes #CRY-165
Closes #CRY-183
=> [ci] Adding matrix job for multiple testbeds

crates/m3/src/builder/table.rs, crates/m3/tests/collatz.rs, crates/m3/tests/fibonacci.rs
This also removes push_one, pull_one
=> [m3] Make push/pull accept subfield columns

crates/field/Cargo.toml, crates/field/benches/main_field_binary_ops.rs, crates/field/benches/main_field_unary_ops.rs
- This MR adds the main binary and unary operations for various packed fields that we care about as listed in #CRY-202
=> [benches] Add micro benchmarks for main field operations

crates/ntt/benches/large_transform.rs, crates/ntt/src/additive_ntt.rs, crates/ntt/src/tests/ntt_tests.rs
- This MR adds more fields to the NTT benchmarking as well as one more batch size parameters.
Closes #CRY-203
=> [benches] NTT micro benches

.github/workflows/benchmark.yml
#CRY-210 Add Perfetto Trace as Artifacts
=> [ci] #CRY-210 Add Perfetto Trace as Artifacts

.github/workflows/nightly-benchmark.yml
=> [ci] #CRY-68 Nightly Benchmark

scripts/nightly_benchmarks.py
Very small MR to add Grøstl runs to the nightly benchmarking script.
=> [benches] Add Grøstl to benchmarking script

.gitignore, Cargo.toml
Bump tracing-profile version to support more informative Perfetto trace file names
=> tracing-profile 0.10.3

.github/workflows/nightly-benchmark.yml, crates/core/benches/prodcheck.rs
- This MR adds the prodcheck necessary for nightly benchmarks
=> [benches] Extract gpa prodcheck for nightly

crates/m3/tests/computed.rs
The test previously had dummy columns with dummy assertions because the computed column was underconstrained, which was leading to an issue in the PIOP layer. By adding a constraint on the computed column, it resolves the issue and moreover tests that the computed column is correct.
=> [m3] Remove dummy columns from computed polynomial test

crates/m3/src/builder/constraint_system.rs, crates/m3/src/builder/test_utils.rs, crates/m3/src/builder/witness.rs, crates/m3/src/gadgets/hash/groestl.rs, crates/m3/src/gadgets/lookup.rs, crates/m3/src/gadgets/u32.rs, crates/m3/tests/collatz.rs, crates/m3/tests/computed.rs, crates/m3/tests/fibonacci.rs, examples/groestl.rs
This is part of a larger effort to remove Underliers from public Binius APIs.
=> [m3] Replace all underliers with packed fields

crates/core/src/protocols/evalcheck/prove.rs
`memoize_partial_evals` received empty `projected_bivariate_claims`, this pr fix this
=> [fix] memoize_partial_evals in Evalcheck

crates/core/src/protocols/evalcheck/evalcheck.rs, crates/core/src/protocols/evalcheck/mod.rs, crates/core/src/protocols/evalcheck/prove.rs, crates/core/src/protocols/evalcheck/subclaims.rs, crates/core/src/protocols/evalcheck/verify.rs
Small MR to add documentation to new changes to evalcheck
=> [evalcheck] Add documentation for Evalcheck

crates/m3/src/gadgets/u32/mod.rs, crates/m3/src/gadgets/u32/sub.rs
This mostly repeats the shape seen in U32Add.
I took a different approach with tests here which reduces duplication and seems a bit cleaner compared to the status quo.
=> [m3] u32 sub gadget

crates/m3/src/gadgets/u32/add.rs, crates/m3/src/gadgets/u32/sub.rs
Just general clean up.
1. Tidy the lingering dbg! in u32sub
2. Move u32add to the same test approach as u32sub
=> [m3] u32 gadgets follow-up

crates/core/src/piop/prove.rs, examples/keccakf_circuit.rs
Reintroduce deleted span used by nightly benchmarks.
=> fix: inf-178: fix nightly benchmarks

crates/m3/Cargo.toml, crates/m3/src/builder/mod.rs, crates/m3/src/builder/test_utils.rs, crates/m3/src/gadgets/lookup.rs, crates/m3/tests/collatz.rs, crates/m3/tests/computed.rs
validate_system_witness by default just does naive witness validation, but an environment variable can be toggled to perform proving + proof verification.
=> [m3] Test utility to simplify testing systems & gadgets

examples/Cargo.toml, examples/keccak.rs
Stacked on top of https://github.com/IrreducibleOSS/binius/pull/259
=> keccak m3 example

crates/core/src/constraint_system/error.rs, crates/core/src/constraint_system/prove.rs, crates/core/src/constraint_system/verify.rs
This MR changes the manual handling of flushes with selectors into `Evalcheck` using composite MLE.
=> [channels] Handle selector logic with CompositeMLE

crates/field/src/arch/aarch64/m128.rs
This one is the same change as in #257 but isolated for faster merging.
=> [field] please clippy

crates/m3/src/builder/table.rs
Based on top of https://github.com/IrreducibleOSS/binius/pull/284, don't merge until that is in.
Also actually add a test for checking if the nesting works properly.
=> [m3] add TableBuilder doc focusing on nesting

crates/m3/src/gadgets/mod.rs, crates/m3/src/gadgets/mul.rs, crates/m3/src/gadgets/u32/add.rs, crates/m3/src/gadgets/u32/sub.rs, crates/m3/src/gadgets/util.rs, crates/m3/tests/mul_div_tests.rs
- This MR adds `MulSU32`, `MulSS32`, `TwosComplement`, `Incr`, `SignConverter` gadgets.
- Added better testing which can possibly be reused in other gadgets.
=> [gadgets] Signed Multiplication Gadgets

crates/m3/src/builder/stat.rs
Based on top of https://github.com/IrreducibleOSS/binius/pull/289, don't merge until that is in.
Closes [CRY-313]
[CRY-313]: https://linear.app/irreducible/issue/CRY-313/bits-per-row
<details>
<summary>
Keccak sample output (snipped)
</summary>
```
table 'Keccak permutation':
* bits per row: 164352
committed: 113152
virtual: 51200
```
</details>
<details>
<summary>
Groestl sample output (snipped)
</summary>
```
table 'Grøstl P permutation':
* bits per row: 26112
committed: 20480
virtual: 5632
```
</details>
=> [m3] Stat returns bits per row

crates/m3/src/builder/column.rs, crates/m3/src/builder/constraint_system.rs, crates/m3/src/builder/error.rs, crates/m3/src/builder/table.rs, crates/m3/src/builder/witness.rs
Small MR to automatically populate with witness index for constants.
=> [M3] Automatic witness population for constants

crates/compute/src/cpu/layer.rs, crates/compute/src/layer.rs, crates/compute/src/memory.rs
Implement for the CPU reference layer. Add a new type combining an FSlice with a subfield degree.
=> SYS-220: Define HAL operation for left_fold

crates/m3/src/builder/structured.rs, crates/m3/src/builder/witness.rs
Bug found and reported by @sai-deng. Thanks!
=> [m3] Fix bug in filling structured columns

crates/m3/src/gadgets/div.rs, crates/m3/src/gadgets/mod.rs, crates/m3/src/gadgets/u32/add.rs, crates/m3/src/gadgets/u32/sub.rs, crates/m3/tests/mul_div_tests.rs
- This MR adds `DivUU32`, `DivSS32` and non packed addition variant for u32 and u64 addition called `WideAdd` 
- This MR depends upon #257 to be merged first
=> [gadgets] Division gadgets for M3

crates/core/src/protocols/gkr_gpa/prove.rs, crates/core/src/protocols/gkr_gpa/verify.rs, crates/core/src/protocols/sumcheck/prove/batch_zerocheck.rs
Switching GKR GPA to using front-loaded sumcheck
=> switch gkr-gpa to front loaded sumcheck

crates/core/src/constraint_system/exp.rs, crates/core/src/piop/prove.rs, crates/core/src/protocols/gkr_exp/witness.rs, crates/core/src/ring_switch/prove.rs, crates/m3/src/builder/constraint_system.rs, examples/u32_mul_gkr.rs
This PR contains a fix for repack_witness in exponentiation, as well as small fixes in PIOP and ring_switch for the case when `n_vars < P::LOG_WIDTH`
=> [FIX] small table exp

crates/core/src/constraint_system/exp.rs, crates/m3/src/builder/constraint_system.rs, crates/m3/src/builder/table.rs, crates/m3/src/gadgets/mul.rs, crates/m3/tests/fibonacci.rs, crates/m3/tests/mul_div_tests.rs
Add unit test to catch issue with compilation bug. Also test cleanups in mul gadget.
=> [m3] Test coverage & cleanups for multiplication gadget

.github/workflows/benchmark.yml
I will need this to properly test the follow up PRs.
=> [ci]: Allow manual trigger of benchmark job

crates/core/src/composition/index.rs, crates/core/src/composition/product_composition.rs, crates/core/src/polynomial/arith_circuit.rs, crates/core/src/polynomial/error.rs, crates/core/src/polynomial/multivariate.rs, crates/core/src/protocols/gkr_exp/compositions.rs, crates/core/src/protocols/sumcheck/eq_ind.rs, crates/core/src/ring_switch/eq_ind.rs, crates/core/src/transparent/constant.rs, crates/core/src/transparent/disjoint_product.rs, crates/core/src/transparent/eq_ind.rs, crates/core/src/transparent/powers.rs, crates/core/src/transparent/select_row.rs, crates/core/src/transparent/shift_ind.rs, crates/core/src/transparent/step_down.rs, crates/core/src/transparent/step_up.rs, crates/core/src/transparent/tower_basis.rs, crates/hal/src/error.rs, crates/macros/src/composition_poly.rs, crates/math/src/error.rs, crates/math/src/fold.rs, crates/math/src/multilinear_extension.rs
This is mostly a mechanical change.
=> Add `actual` to every query size error

crates/core/src/merkle_tree/binary_merkle_tree.rs, crates/core/src/polynomial/arith_circuit.rs, crates/hash/Cargo.toml, crates/hash/src/vision/digest.rs, crates/math/src/fold.rs, crates/utils/src/mem.rs
We already have slice_assume_init at home.
=> [utils] prefer homegrown slice_assume_init

Cargo.toml, crates/core/benches/composition_poly.rs, crates/field/benches/byte_sliced.rs, crates/field/benches/packed_extension_mul.rs
After https://github.com/bheisler/criterion.rs/pull/860
=> deps: bump criterion

crates/m3/src/builder/indexed_lookup.rs
Added `ArithCircuit`s for the Incr lookup table expression, and changed it from a committed to a fixed column in the lookup test.
=> [m3] Fixed Column for Increment Lookup tests

crates/ntt/src/additive_ntt.rs, crates/ntt/src/multithreaded.rs
=> [ntt] Make multithreaded use NTT methods

crates/field/src/underlier/scaled.rs, crates/m3/src/builder/channel.rs, crates/m3/src/builder/witness.rs, crates/m3/src/gadgets/barrel_shifter.rs, crates/m3/src/gadgets/hash/groestl.rs, crates/m3/src/gadgets/lookup.rs, crates/m3/src/gadgets/mul.rs, crates/m3/tests/mul_div_tests.rs
Fixing a bunch of typos that I've gathered throughout several past weeks.
=> [chore] typos

crates/m3/src/builder/witness.rs
Creating an Col out of thin air is discouraged and we don't need it there in any
case. This changeset just inlines the `get` removing all the unnecessary logic.
=> [m3] eval_expr doesn't conjure Col out of thin air

crates/fast_compute/src/layer.rs, crates/fast_compute/tests/layer.rs
=> [compute] Implement `FastCpuLayer::fold_right `
