IrreducibleOSS/binius

- .github/workflows/mirror.yml
GitHub Workflow to mirror repository and its `main` branch to GitLab
> [ci]: Setting Up Mirror to GitLab

- .cargo/config.toml
- Cargo.toml
This MR addresses tow issues that make `cargo test` slow:
1. Thin LTO slows down compilation of all the crates a bit.
2. It takes quite a time to compile and link all the examples with `test` profile which are not actually executed. So I've added an alias to compile and run tests only for fast local usage.
But the main problem is still with `binius_field` tests compilation taking too long when `opt_level` is 1:
And we can't change this setting to 0 even for this crate only, otherwise circuit tests are becoming too slow and test running time only increases. The problem seems to be that one of the codegen units in the crate takes more than a minute to compile while other ones are small:
That seems to be a problem how those codegen units are created by `rustc`, increasing max number of units …
> Improve test compilation time

- crates/core/src/polynomial/arith_circuit.rs
- crates/field/src/aes_field.rs
- crates/field/src/binary_field.rs
- crates/field/src/binary_field_arithmetic.rs
- crates/field/src/polyval.rs
- crates/math/src/arith_expr.rs
In contrast to `TowerField::TOWER_LEVEL`, `TowerField::binary_tower_level(self)` returns the smallest tower level that can fit the current value. This can be useful for shrinking field values to the smaller container that fits them, for the purpose of making arithmetic operations (in particular multiplication) cheaper
Note that depending on the tower family, not all tower level values are valid.
- For BinaryField, tower levels 0, 1, 2, 3, 4, 5, 6, 7 are valid
- For AESTowerField, tower levels 0, 3, 4, 5, 6, 7 are valid
- For Polyval, tower levels 0, 7 are valid
> [field] Add TowerField::min_tower_level(self), and use it to derive ArithExpr tower_level from its constants

- crates/math/src/matrix.rs
The check `assert!(i < self.m);` is already done in `self.row_mut(i)`
> [matrix]: simplify scale_row

- crates/field/src/arch/x86_64/m128.rs
- crates/field/src/arch/x86_64/m256.rs
- crates/field/src/arch/x86_64/m512.rs
For some arch-specific reason the version I tuned using benchmarks on Intel CPU was extremely slow on a SuperMicro, making element access in byte-sliced fields 10x slower. The curios thing is that comparing with all possible SIMD tricks (shuffle, lane bit-shifting) the most straightforward version shows the best performance. Also it is in general slightly faster on Intel CPUs as well.
Apart from microbenchmark I see Keccak performance being better by ~8% on SuperMicro after these changes as well, but potentially much bigger gain will be with the byte-sliced fields.
> Optimize SIMD element access for Zen4 architecture as well.

- crates/core/src/constraint_system/prove.rs
Refactor tower level detection by replacing `arith_expr_base_tower_level` function calls with direct implementation of `composition.binary_tower_level()`, simplifying type conversion and check logic.
> refactor: Use binary_tower_level for base field detection

- scripts/nightly_benchmarks.py
A small MR to remove the groestl run from the nightly benchmarking script
> [scripts] Remove groestl run from benchmark script

- crates/core/src/protocols/gkr_gpa/gpa_sumcheck/prove.rs
- crates/core/src/protocols/gkr_gpa/gpa_sumcheck/tests.rs
- crates/core/src/protocols/gkr_gpa/prove.rs
- crates/core/src/protocols/sumcheck/common.rs
- crates/core/src/protocols/sumcheck/error.rs
- crates/core/src/protocols/sumcheck/prove/prover_state.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/core/src/protocols/sumcheck/prove/zerocheck.rs
- crates/core/src/protocols/sumcheck/tests.rs
- crates/core/src/protocols/sumcheck/zerocheck.rs
- crates/hal/src/backend.rs
- crates/hal/src/cpu.rs
- crates/hal/src/error.rs
- crates/hal/src/sumcheck_evaluator.rs
- crates/hal/src/sumcheck_round_calculator.rs
- crates/math/src/arith_expr.rs
- crates/math/src/univariate.rs
This MR adds support for the Karatsuba infinity point when interpolating, where we take a binary subspace evaluation domain and replace the third point (after zero and one) with an infinity: 
$$
f(z, xs) = f(0, xs) + z (f(1,xs) - f(0,xs)) 
$$
$$
f(\infty, xs) = lim_{z \rightarrow \infty} \frac{f(z,xs)}{z} = f(1,xs) - f(0, xs)
$$
This saves a multiplication in one point (which is a large-by-large in POLYVAL case) and allows sumchecking quadratic constraints without using multiplications for interpolation at all. There is a caveat though - we cannot use the original composition polynomial $C$ in this point, and should use $lim_{z \rightarrow \infty} \frac{C(f(z, xs))}{{z^{deg C}}} z^{deg C}$ instead. Luckily having `expression()` in `CompositionPolyOS` and `ArithExpr`/`ArithCircuitPoly` …
> Karatsuba interpolation in sumchecks

- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/reed_solomon/reed_solomon.rs
- crates/hash/src/vision.rs
- crates/math/src/binary_subspace.rs
- crates/ntt/benches/additive_ntt.rs
- crates/ntt/src/additive_ntt.rs
- crates/ntt/src/dynamic_dispatch.rs
- crates/ntt/src/error.rs
- crates/ntt/src/multithreaded.rs
- crates/ntt/src/odd_interpolate.rs
- crates/ntt/src/single_threaded.rs
- crates/ntt/src/tests/ntt_tests.rs
- crates/ntt/src/tests/reference.rs
- crates/ntt/src/twiddle.rs
This is a refactor that
* Changes `AdditiveNTT` to be parameterized by `F: Field` instead of `P: PackedField`
* Exposes the NTT domain as a `BinarySubspace`
These changes are intended to support future changes that enable NTTs on FRI-compatible additive subspaces. The way NTT domains work currently, additive NTTs created for differently sized domains over the same basis elements are not FRI-compatible.
> [ntt] Refactor AdditiveNTT to support more choices of NTT domain

- crates/circuits/src/arithmetic/u32.rs
- crates/circuits/src/blake3.rs
- crates/circuits/src/lasso/sha256.rs
- crates/circuits/src/sha256.rs
- crates/circuits/src/unconstrained.rs
This PR completes set of gadgets to implement Blake3 [compression](https://github.com/BLAKE3-team/BLAKE3/blob/master/reference_impl/reference_impl.rs#L74) circuit. [Permutation](https://github.com/BLAKE3-team/BLAKE3/blob/master/reference_impl/reference_impl.rs#L66), which is a part of compressing, is not yet entirely constrained - @onesk suggested to use channel balancing constraint here (according to the [following](https://gitlab.com/IrreducibleOSS/binius/-/merge_requests/601/diffs#e209d5579974b8e6590048359fdbc677201f6c83_0_895) example in KeccakSponge), which I'm going to address for the Blake3 case in a subsequent PR.
> feat: Blake3 compression

- crates/core/src/protocols/fri/error.rs
Corrects a duplicated word "be be" in the FirstFoldArityTooSmall error message, replacing it with "should be" for better clarity.
> Fix typo in FRI error message

- crates/core/benches/prodcheck.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/constraint_system/verify.rs
- crates/core/src/protocols/gkr_gpa/prove.rs
- crates/core/src/protocols/gkr_gpa/tests.rs
- crates/core/src/protocols/gkr_gpa/verify.rs
Adapting GKR GPA to support varying evaluation orders and weakening type bounds to enable byte slice field usage.
Unfortunately work still needs to happen for a potential POLYVAL dethrone (if it's even possible), as evidenced by latest SM benchmarks:
```
gpa_polyval_128b/n_vars=12
time:   [36.455 ms 36.751 ms 37.046 ms]
thrpt:  [1.1056 Melem/s 1.1145 Melem/s 1.1236 Melem/s]
gpa_polyval_128b/n_vars=16
time:   [81.938 ms 82.689 ms 83.378 ms]
thrpt:  [7.8601 Melem/s 7.9256 Melem/s 7.9982 Melem/s]
gpa_polyval_128b/n_vars=20
time:   [278.98 ms 282.01 ms 284.48 ms]
thrpt:  [36.859 Melem/s 37.183 Melem/s 37.586 Melem/s]
gpa_polyval_128b/n_vars=24
time:   [2.6647 s 2.6853 s 2.7066 s]
thrpt:  [61.987 Melem/s 62.478 Melem/s 62.962 Melem/s]
gpa_polyval_128b_high_to_low/n_vars=12
time:   [35.173 ms …
```
> Configurable evaluation order in GPA

- crates/core/src/piop/commit.rs
- crates/utils/src/sparse_index.rs
Adds more methods that are similar to other std collection methods
> [sparse_index] Extend SparseIndex API, and remove `T: Clone` requirement

- crates/ntt/benches/large_transform.rs
This small MR adds Bytesliced Additive NTT and comparable packed AES Benchmarks. Note that the ByteSliced benchmark does not take into account data transposition. Preliminary investigations indicate Bytesliced NTT to be faster than `AESTowerField` on non gfni machines and seems to perform worse on machines with gfni instructions.
```
slow/transform/single-thread/precompute/field=BinaryField32b/log_dim=16/log_inv_rate=1/log_b=6
time:   [524.57 ms 537.78 ms 553.70 ms]
thrpt:  [57.793 MiB/s 59.504 MiB/s 61.003 MiB/s]
change:
time:   [+0.8019% +3.2481% +6.1817%] (p = 0.04 < 0.05)
thrpt:  [-5.8218% -3.1459% -0.7955%]
Change within noise threshold.
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
slow/transform/multithread/precompute/field=BinaryField32b/log_dim=16/log_inv_ra …
```
> [benches] Add Bytesliced additive NTT benchmark

- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/u32.rs
- crates/m3/tests/collatz.rs
Moves `Table::add_*` methods to `TableBuilder::add_*`, which also supports namespacing.
To add a namespace before passing the TableBuilder to a gadget, you can do something like:
```rs
let inner_table = Table::new(..)
let table = TableBuilder::new(&mut inner_table)
U32Add::new(
&mut table.with_namespace("u32add"),
..
)
```
> [m3] Add TableBuilder with namespacing

- crates/core/src/protocols/gkr_exp/tests.rs
When running tests locally with the standard stack size I found that some of the tests are failing due to stack overflow on initialization which is pretty confusing. The reason is big arrays of test data allocated on the stack. I'm not against having big stack size setting by default, but here it seems that we are doing it for now reason and better just use dynamic-allocated memory.
> Fix stack overflow errors for unit tests

- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/expr.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/tests/collatz.rs
The Collatz example was underconstrained and didn't check the evenness of values in the evens table and oddness of values in the odds table. This requires a few features and bug fixes:
* Handling of selected columns
* Bug fix for LinearCombination oracles indexing improperly into the table
* Ability to add constants to expressions
> [m3] Fix underconstained Collatz example

- crates/math/src/fold.rs
The notorious `MultilinearExtension::evaluate_partial_high` is based on individual scalar access and thus works spectacularly bad with byte sliced fields. While high-to-low sumchecks perform folding using specialized inplace routine, the overhead of first transition from MLE to folded representation remains and needs to be optimized.
Correctly performing this specialization cannot use individual scalar access like in low-to-high for the aforementioned reasons. Furthermore, for the generic case of `P != PE` we need to do spreads on either `P` or `PE` (depending on respective `LOG_WIDTH`), which requires dynamically checking for `PackedExtension` relation. Lacking that ability and being reluctant to propagate this bound across the whole codebase, the decision is to specialize the `P == PE` …
> Specialized left lerp fold for P==PE

- crates/m3/src/builder/table.rs
These assertions accidentally got dropped in a previous change
> [m3] Add useful assertions for add_packed, add_shifted

- crates/core/src/protocols/sumcheck/front_loaded.rs
We can detect an `ExpectedFinishRound` error and finish directly without having to compute the degree (which is computed only if `last_coeffs_or_sum` is appropriate).
> [sumcheck]: return early if `ExpectedFinishRound`error

- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/expr.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/u32.rs
- crates/m3/tests/collatz.rs
Also removes any mention of pack_factor, which can be confusing name-wise, since we also have packed virtuals/packed fields.
This is nice because `Col<B1, 32>` generally feels more familiar than `Col<B1, 5>`, and pairs more reads more nicely together with `Col<B32, 1>`
> [m3] Switch from LOG_VALS_PER_ROW to VALUES_PER_ROW

- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/reed_solomon/reed_solomon.rs
- crates/ntt/benches/additive_ntt.rs
- crates/ntt/benches/large_transform.rs
- crates/ntt/src/additive_ntt.rs
- crates/ntt/src/dynamic_dispatch.rs
- crates/ntt/src/multithreaded.rs
- crates/ntt/src/odd_interpolate.rs
- crates/ntt/src/single_threaded.rs
- crates/ntt/src/tests/ntt_tests.rs
- crates/ntt/src/tests/reference.rs
Previously there was no way to specify an NTT forward/inverse transform narrower than a packing width, which incurred unneeded `PackedFieldIndexable` constraints in univariate skip. This PR adds `log_n` as the fourth parameter to `AdditiveNTT` methods and updates usage sites accordingly.
> Add log size parameter to AdditiveNTT methods

- crates/m3/src/builder/table.rs
- crates/m3/src/gadgets/u32.rs
- crates/m3/tests/fibonacci.rs
Depends on this being merged first to fix failing tests:
- https://github.com/IrreducibleOSS/binius/pull/95
Other changes:
- Add push/pull to TableBuilder interface
- Fix U32Add gadget not populating zout when there is no carry bits set
> [m3] Add fibonacci example/tests

- crates/core/src/polynomial/arith_circuit.rs
- crates/m3/Cargo.toml
- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/error.rs
- crates/m3/src/builder/expr.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/tests/collatz.rs
- crates/m3/tests/fibonacci.rs
- crates/macros/src/composition_poly.rs
- crates/math/src/arith_expr.rs
- crates/math/src/composition_poly.rs
- crates/math/src/error.rs
The main feature here is the `TableWitnessIndexSegment::eval_expr` method. This showed up as a useful method as I was implementing the Groestl circuit.
The implementation of this method could be optimized more, but it's probably OK for now. It uses `ArithCircuitPoly` batch evaluation. If the witness segments are really large, this could be problematic. I left a comment to explain that.
I also did some refactors to the M3 crate to
* reduce duplicated information in the `ColumnId` struct,
* rename `VALUES_PER_ROW` to `V` in most cases (it's common throughout the whole crate, we only need to explain it once and then use the shorthand)
* make the `WitnessIndex` hold a reference to the constraint system to make it easier for the witness index methods to query information from it
> [m3] Add utility method to witness index for evaluating expressions

- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/tests/computed.rs
- crates/math/src/arith_expr.rs
Attempt to fix #104
The test I wrote is quite ugly, I only did it to ensure I wasn’t missing something trivial. Unless contraindicated, I think it's better to remove it. (Otherwise I should improve it)
As for the PR itself, it seems pretty straightforward, I hope I don't miss anything. 2 remarks:
- I introduced 2 new functions for `ArithExpr`: `vars()` and `vars_sorted()`, and there may be confusion because `arithm_circuit.n_vars()` returns the max variable index + 1, which is different in general from `arithm_circuit.vars.len()` (`Var(0) * Var(5)` -> `n_vars()` = 6 but `vars().len()` = 2). Maybe we should rename ?
- While writing the test, I could not create an m3 `Expr` based on columns / field elements with different tower heights. Is there a raison not to allow this ?
> Expose computed columns from the M3 Table interface

- crates/m3/src/builder/error.rs
- crates/m3/src/builder/witness.rs
- crates/m3/tests/collatz.rs
- crates/m3/tests/fibonacci.rs
This reduces boilerplate when working with packed columns (which is typical when flushing columns after working with bit-representations). You now can decide whether to fill the packed or unpacked column. They both try to borrow the same RefCell mutably, so if you try to borrow both at the same time your code will panic.
> [m3] Use shared witness data for packed columns

- crates/core/src/polynomial/multivariate.rs
- crates/field/src/packed.rs
- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/tests/collatz.rs
Adding a repeating constant actually creates 2 oracles:
- transparent
- a repeating version of the transparent poly
We get around needing to fill the transparent witness, or even returning an id for it by having it alias the same underlying data as the repeating transparent (but with a different length value).
> [m3] Add support for repeating constants

- crates/m3/Cargo.toml
- crates/m3/src/builder/column.rs
- crates/m3/src/builder/expr.rs
- crates/m3/src/gadgets/hash/groestl.rs
- crates/m3/src/gadgets/hash/mod.rs
- crates/m3/src/lib.rs
- crates/math/src/arith_expr.rs
This is the first gadget towards building the Grøstl hash function with the M3 crate.
The main trickiness is constraining the hash over the canonical B8 tower field instead of the AES tower.
The input to the S-box is an `Expr` instead of a `Col` because the input can be a column with a round constant added, and it's more efficient to treat that as an expression than a linear combination column.
> [m3] Create gadget for the Rijndael S-box

- crates/core/src/protocols/fri/common.rs
- use sumcheck error of 2 ⋅ ℓ' / |𝒯_τ|, instead of ℓ' / |𝒯_τ|. the missing factor of 2 is a carry-over from a previous time, when we were using (the strong version of) Angus's § 3 optimization. now, because of row-batching, we can't do this anymore—our sumcheck is no longer with an eq-indicator.
- calculate the number of queries in one shot, instead of using only `security_bits` and then adding integers post-hoc. to do this, we just need to subtract the `folding_err` and `per_query_err` from 2^{-security_bits} before taking log_2 and dividing the result by log_2(per_query_err).
> fixes in FRI `calculate_n_test_queries`

- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/sumcheck/common.rs
- crates/core/src/protocols/sumcheck/eq_ind.rs
- crates/core/src/protocols/sumcheck/error.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/protocols/sumcheck/univariate.rs
- crates/core/src/protocols/sumcheck/univariate_zerocheck.rs
- crates/math/src/error.rs
- crates/math/src/univariate.rs
Two leftovers from #114:
1) `verify_sumcheck_outputs` returns proper `VerificationError`s instead of panicking
2) `EvaluationDomainFactory` is back to having `create` method only, all domains of size three and up include the Karatsuba infinity point
Regarding the latter change, most univariate skip code requires explicit construction of the domain from the binary subspace now, which I actually consider an improvement, because univariate skip relies on domain structure and it's good to have this specified explicitly (especially with the potential change to novel polynomial basis representation of the univariatized round polynomials).
> EqIndSumcheck follow-ups

- crates/core/Cargo.toml
- crates/core/benches/sumcheck.rs
- crates/ntt/benches/large_transform.rs
This small MR adds the sumcheck benchmark over Bivariate product with `n_vars = 20` as well as shortens the name for NTT benchmarks
> [benches] Add sumcheck micro benchmarks

- crates/circuits/src/arithmetic/mod.rs
- crates/circuits/src/arithmetic/mul.rs
- crates/circuits/src/arithmetic/static_exp.rs
- examples/Cargo.toml
- examples/u32_mul_gkr_exp_lookups.rs
An optimized by commits version of Mul that uses lookups for static exponentiation and gkr_exp for dynamic exponentiation.
This is much faster than my previous implementation, but still slower  than gkr_exp on supermicro (26.92s vs 24.87s).
Commits for 2^{24} muls :
| Name                   | log_rows | TOWER_LEVEL |
|------------------------|---------|-------------|
| xin_low_exp_res       | 24      | 6           |
| g table              | 16      | 7           |
| xin_high_exp_res      | 24      | 6           |
| g_16 table           | 16      | 7           |
| xin_exp_result       | 24      | 6           |
| yin_exp_result       | 24      | 6           |
| cout_0               | 24      | 4           |
| cout_1               | 24      | 4           |
| cout_2               | 24      | …
> [Mul] gkr exp + lookups 

- crates/m3/src/builder/table.rs
This PR exposes the ability to set non-zero constraints by adding a method in table.rs
> Add assert_nonzero method to table.rs

- crates/m3/src/builder/channel.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
Add `pull_selected` and `push_selected` functions to `TableBuilder` and `TablePartition`, allowing API consumers to provide selectors for flushes.
The `StepDown` selector is used as a fallback in case one is not provided.
> feat: enable flushes with custom selectors on `m3`

- crates/core/src/protocols/sumcheck/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/prover_state.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/hal/src/backend.rs
- crates/hal/src/cpu.rs
- crates/hal/src/sumcheck_evaluator.rs
- crates/hal/src/sumcheck_round_calculation.rs
- crates/math/src/arith_expr.rs
* Adding support for const eval suffix per composition
* Round calculator queries/interpolates only the multilinears accessed in the given subcube (using information obtained from `vars_usage` in `ArithExpr`)
* `EqIndSumcheckProver` determines const eval suffix symbolically from composition `ArithExpr` and `nonzero_eval_prefixes`
> Const eval suffix per composition, with symbolic derivation.

- crates/circuits/src/arithmetic/static_exp.rs
- crates/circuits/src/builder/witness.rs
- crates/circuits/src/plain_lookup.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/sumcheck/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/prover_state.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/core/src/witness.rs
- crates/hal/src/backend.rs
- crates/hal/src/cpu.rs
- crates/hal/src/sumcheck_evaluator.rs
- crates/hal/src/sumcheck_round_calculation.rs
- crates/math/src/arith_expr.rs
> depends on #162 
- augments `plain_lookup` with an ability to use the permuted version of `lookup_t` committed in the non-increasing multiplicity order; that allows leveraging nonzero scalars prefixes optimization in flush sumchecks, and, eventually, GKR reductions
- interface changed to Lasso-like, but taking multiplicities as an additional prover parameter (instead of `u->t` mapping in Lasso)
- supports "wide" lookups (many columns of the same type), but committing to the permuted lookup version within the gadget enforces all the columns to be of the same `FTable` type and with `PackedFieldIndexable` packing for the sake of simplicity
> Efficient plain lookups

- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/witness.rs
This change was missing in #159. Without it, I was getting size mismatches between columns when pushing/pulling from empty tables to the channel.
I'm also changing the signatures of `fill` in `TableFiller` trait. I'm adding `+ Clone` in order to reuse the events (see for example [this use case](https://github.com/IrreducibleOSS/zCrayVM/blob/c63d851780e6ddeb75536ece51868b3dac635c91/assembly/src/event/arithmetization/ret.rs#L132))
> [m3] Make `WitnessIndex` tables a vec of options

- crates/core/src/piop/commit.rs
- crates/core/src/piop/error.rs
- crates/core/src/piop/prove.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/tests/fibonacci.rs
When the smallest committed column is too small, it currently causes an `OracleTooSmall` error in the PIOP compiler. This correctly ensures that table capacities get padded enough to avoid the problem.
> [m3] Fix for proving when table size is too small

- crates/core/benches/composition_poly.rs
- crates/core/src/composition/index.rs
- crates/core/src/polynomial/arith_circuit.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/hal/src/sumcheck_evaluator.rs
- crates/hal/src/sumcheck_round_calculator.rs
- crates/m3/src/builder/witness.rs
- crates/macros/src/composition_poly.rs
- crates/macros/tests/arithmetic_circuit.rs
- crates/math/src/composition_poly.rs
- crates/math/src/error.rs
- crates/math/src/lib.rs
- crates/math/src/rows_batch.rs
It appeared that we are creating that big batch of values when proving Vision32 that just checking if all the rows in the batch are of the same length takes signifficant amount of time since we are doing it for each `batch_evaluate` call. in this PR we introduce a special struct that guarantees that all the rows are of the same length by checking it at the moment of creation. Also I like this approach more because this struct helps self-describe the argument of `batch_evaluate` .
For proving Vision32 this saves about 15% of overall time.
> Introduce a struct for a batch of rows of the same length

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/piop/prove.rs
- crates/core/src/piop/verify.rs
This is a quick modification to make the FRI-Binius PCS use high-to-low sumcheck. The trick is simply that we bit-reverse the multilinear coefficients before committing. This has the effect of bit-reversing their encodings as well, and everything works pretty nicely.
I'm not that happy about re-introducing the dependency on p3-util or `PackedFieldIndexable`, but this was the fastest way to get it working. @GraDKh maybe you have ideas how to fix that?
> [piop] Make piop compiler work with high-to-low sumcheck

- crates/circuits/src/vision.rs
- crates/field/src/aes_field.rs
- crates/field/src/binary_field.rs
- crates/field/src/extension.rs
- crates/field/src/polyval.rs
- crates/m3/src/gadgets/hash/groestl.rs
- crates/math/src/binary_subspace.rs
The `ext_basis<FExt, FSub>` function is now an easy way to get field extension bases.
> [field] Friendlier function for getting field bases

- crates/field/src/binary_field.rs
- crates/field/src/underlier/small_uint.rs
- crates/m3/src/builder/channel.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/mod.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/test_utils.rs
- crates/m3/src/gadgets/lookup.rs
- crates/m3/src/gadgets/mod.rs
This is a port of the "plain" lookup argument. In future PRs, we will
1. Optimize the grand product argument prover computations by leveraging the zero-extended structure of the multiplicity bit columns.
2. Create a mechanism for computing multiplicities into indexed lookup tables without requiring the emulation phase to count multiplicities itself.
> [m3] Gadget to push values to a channel with multiplicity

- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/gkr_exp/batch_prove.rs
- crates/core/src/protocols/gkr_exp/common.rs
- crates/core/src/protocols/gkr_gpa/prove.rs
- crates/core/src/protocols/sumcheck/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/mod.rs
- crates/core/src/protocols/sumcheck/prove/prover_state.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/core/src/protocols/sumcheck/prove/zerocheck.rs
- crates/hal/src/sumcheck_multilinear.rs
* Instead of always taking an `M: MultilinearPoly` transparent, `ProverState` ingests `SumcheckMultilinear` directly
* `EqIndSumcheckProverBuilder` was augmented with `no_switchover` constructor, which allows specifying folded `Vec<P>` large field representations by value
Rationale:
* GPA sumchecks operate on large field _unique_ witnesses; using `immediate_switchover_heuristic` still allocates 1.5x witness data, which is totally avoidable when witness is passed by value
* (continuation of the above) Shorter-than-power-of-two folded multilinears are explicitly supported by the HAL, which is useful for optimizing GPAs coming from plain lookups
* In zerocheck univariate round we currently skip at most 7 rounds, which results in folded multilinear still being larger than witness column for …
> Support for no switchover in sumchecks

- crates/circuits/src/builder/constraint_system.rs
- crates/core/src/constraint_system/channel.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/constraint_system/verify.rs
- crates/core/src/protocols/evalcheck/evalcheck.rs
- crates/m3/src/builder/channel.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/error.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/lookup.rs
- crates/m3/tests/fibonacci.rs
This adds the option to define tables in M3 that are required to have power-of-two size. These tables will have selectors omitted. This also modifies the constraint proving protocol to skip the selected sumcheck when the table is power-of-two-sized.
**Why not just omit selectors if the table size in the instance happens to be a power of two?** This is a reasonable alternative. However, I ultimately want the property that the oracle IDs and types in the compiled constraint system are independent of the table sizes in the instance. This is necessary for reduction planning. Also, it seems unlikely that large tables that are not statically known to be power-of-two sized will end up being power-of-two sized.
> [m3] Ability to define power-of-two-sized tables

- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/sumcheck/eq_ind.rs
- crates/core/src/protocols/sumcheck/error.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/prover_state.rs
- crates/hal/src/sumcheck_folding.rs
- crates/hal/src/sumcheck_multilinear.rs
- crates/hal/src/sumcheck_round_calculation.rs
- crates/math/src/fold.rs
> Depends on #188 
Attempts to implement more efficient GPA sumchecks for plain lookups proved that existing zero extend multilinear support in sumcheck is inadequate - things like "offset bivariate products" of the form `(a+offset)*(b+offset)-offset` pollute too much verifier code for what is essentially a prover optimization.
Hence this PR replaces `nonzero_scalars_suffix` params with `const_suffix`, which is a pair `(F, usize)`. Sumcheck folding/round calculation and `EqIndSumcheck` const eval suffix determination are augmented to support this functionality.
> Arbitrary multilinear const suffix in sumcheck

- crates/compute/Cargo.toml
- crates/compute/src/alloc.rs
- crates/compute/src/cpu/memory.rs
- crates/compute/src/cpu/mod.rs
- crates/compute/src/lib.rs
- crates/compute/src/memory.rs
@alsrdn and I learned in the course of pair programming that having `FSlice` traits that can subslice themselves is problematic. (It's complicated to explain: the subslices have a different type than the parent because they are parameterized by another lifetime (a subscope), and they're no way to additionally indicate to the type system the relationship at an abstract level).
Instead I made a `ComputeMemory` trait for manipulating memory references & slices. The eventual `ComputeLayer` trait will either have a `ComputeMemory` as a parent trait or associated type.
This also includes a dead-simple bump allocator implementation that is generic over `ComputeMemory`.
> [compute] Initial memory interface

- crates/field/benches/packed_field_init.rs
- crates/field/benches/packed_field_iter.rs
- crates/field/src/arch/portable/byte_sliced/packed_byte_sliced.rs
This gives 2-10x speedup depending on the scalar size and width
> Implement optimized initialization and iteration for byte sliced fields using transposition

- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/evalcheck/tests.rs
Run evalcheck tests using the byte sliced field to ensure compatibility.
> [Evalcheck] byte-sliced tests

- crates/m3/Cargo.toml
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/error.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/hash/groestl.rs
- crates/m3/src/gadgets/lookup.rs
- crates/m3/tests/collatz.rs
- crates/m3/tests/computed.rs
- crates/m3/tests/fibonacci.rs
- examples/groestl.rs
Previously all table sizes needed to be specified when the witness index was created. There's enough information in the `fill_table_sequential` and `fill_table_parallel` calls to initialize the table indexes properly, so this change allows the table initialization to use the data from those calls. When creating the `Statement` for constraint system compilation, it's recommended to get the table information from the witness, or in the verifier's case, received from the prover.
> [m3] Refactor away duplication of table size specification

- crates/core/src/constraint_system/exp.rs
- crates/core/src/protocols/gkr_exp/tests.rs
- crates/core/src/protocols/gkr_exp/witness.rs
Add PExpBase to the gkr_exp witness, which allows reducing memory usage for storing it.
The witness supports all PackedField types, including Polyval.
> Optimize GKR exp protocol with packed subfield types

- crates/core/src/protocols/evalcheck/error.rs
- crates/core/src/protocols/evalcheck/evalcheck.rs
- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/evalcheck/tests.rs
- crates/core/src/protocols/evalcheck/verify.rs
- crates/core/src/protocols/greedy_evalcheck/prove.rs
- crates/core/src/protocols/greedy_evalcheck/verify.rs
- crates/core/src/transcript/mod.rs
This PR introduces deduplication for EvalCheck claim prove/verify steps, which positively impacts both proof size and verification time.
The core idea is to leverage Advice — supplementary information the prover provides to the verifier. If a claim has already been proven/verified, the prover includes its position within the `round_claims` list. This allows the verifier to efficiently confirm the validity of a duplicate claim without the need for an additional search through the list.
The proving process has been updated and now consists of three key steps:
1. **Evaluation Memoization with modified BFS** 
Since the order of processing stamps is not important, we take full advantage of multithreading  
for improved performance.
2. **Prove multilinears**  
Constructs both the proofs and the …
> [Evalcheck] Deduplication using advices

- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/sumcheck/prove/oracles.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/protocols/sumcheck/prove/zerocheck.rs
- crates/core/src/protocols/sumcheck/univariate.rs
- crates/core/src/protocols/sumcheck/zerocheck.rs
> Depends on #200 
Leverages newly introduced NTT non-strided batching and a packed spread multiplication by equality indicator to remove `PackedFieldIndexable` bound from all zerocheck routines, making byte sliced usage feasible.
> Removing PackedFieldIndexable from univariate skip zerocheck.

- crates/core/src/constraint_system/channel.rs
We noticed it was a bit tedious to debug unbalanced channels as the returned error isn't so descriptive (only the channel ID is mentioned).
I added some tracing to get the unbalanced flushes displayed at the `DEBUG` level.
> Add tracing for unbalanced flushes

- crates/core/src/piop/prove.rs
- crates/core/src/piop/tests.rs
- crates/core/src/piop/verify.rs
Previously, when a committed column had no evaluation claims, the PIOP compiler would throw a `Math(PiecewiseMultilinearIncompatibleEvals` error. While an unconstrained committed is bad, this should get warned about at a higher level, not throw a confusing error deep in the stack.
> [piop] Fix failing PIOP case when there are no evaluation claims

- crates/core/src/piop/commit.rs
- crates/core/src/piop/error.rs
- crates/core/src/piop/prove.rs
- crates/core/src/ring_switch/common.rs
- crates/core/src/ring_switch/prove.rs
- crates/core/src/ring_switch/tests.rs
This relaxes the `ring_switch` and `piop` modules to handle committed polynomials that are smaller than the size of a packed large element and eliminates the `OracleTooSmall` error. We handle this case by committing the polynomial as it's MLE over the larger hypercube, which corresponds to repeating it's evaluations. The integration test in `ring_switch` module is updated to exercise this code path.
> [piop] Handle arbitrarily small committed polynomials

- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/ring_switch/eq_ind.rs
- crates/core/src/transparent/eq_ind.rs
- crates/core/src/transparent/shift_ind.rs
- crates/core/src/witness.rs
Byte-sliced PackedFields have a large width, so using from_values may lead to incorrect n_vars and unexpected behavior. It’s better to replace `MultilinearExtension::from_vales` to `MultilinearExtension::new`.
> Change MultilinearExtension::from_vales to MultilinearExtension::new

- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/lookup.rs
This was identified by @sai-deng in https://github.com/IrreducibleOSS/binius/pull/185.
This issue is caused by the solution of https://github.com/IrreducibleOSS/binius/pull/170, which makes it possible for tables to be automatically allocated capacity exceeding their event count. That works fine for regular tables, but not lookup tables that are `power_of_two_sized`. However, that solution is now obsolete because of an alternative fix in https://github.com/IrreducibleOSS/binius/pull/227, so this adds a test and assertion and rolls the change back.
> [m3] Fix the small-table flushing bug for lookups

- crates/core/src/fiat_shamir/hasher_challenger.rs
- crates/core/src/protocols/fri/prove.rs
- crates/core/src/protocols/fri/tests.rs
- crates/core/src/protocols/fri/verify.rs
- crates/core/src/transcript/mod.rs
Update the batch_size of the `terminate_codeword` Merkle tree so that it has exactly `inv_rate` leaves
> Fix shape of terminal FRI oracle

- crates/m3/src/builder/constraint_system.rs
If you try to display the constraint system in the m3/collatz test, you would get
```
thread 'arithmetization::test_collatz_validate_witness' panicked at /Users/pepyakin/dev/irreducible/binius/crates/m3/src/builder/constraint_system.rs:58:47:
index out of bounds: the len is 3 but the index is 3
```
I am not 100% sure in the fix, but it seems like `column_indices` are in the `table.columns` index space.
> [m3] fix OOB in Display impl of ConstraintSystem

- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/ntt/src/single_threaded.rs
- crates/ntt/src/tests/ntt_tests.rs
Changes in #200 removed the need for the domain size to be at least twice the packed field width, but the check remained. This followup PR removes this overly conservative restriction.
> Remove overly conservative domain size check in AdditiveNTT

- crates/circuits/src/blake3.rs
- examples/blake3_circuit.rs
This PR re-implements Blake3 compression circuit more optimally for verifier using "horizontal" witness population (inspired by keccakf), which allows proving multiple compressions at once. 
There are couple of questions to reviewers:
1) How should I constrain the `state_i_8` [column](https://github.com/storojs72/binius/blob/as/blake3-horizontal/crates/circuits/src/blake3.rs#L475) properly? Initially, I had a following issue (when running the entire prove / verify example):
```
PIOPCompilerError(Math(PiecewiseMultilinearIncompatibleEvals { actual: 88, expected: 91 }))
or
Error: PIOP compilation error: binius_math error: there are a total of 50 polynomials, according to n_pieces_by_vars, while you have provided evaluations for 53
Caused by:
0: binius_math error: there are a total of 50 …
```
> [circuits] Optimised Blake3 compression

- crates/circuits/src/lib.rs
- crates/core/benches/composition_poly.rs
- crates/core/src/composition/index.rs
- crates/core/src/constraint_system/validate.rs
- crates/core/src/oracle/composite.rs
- crates/core/src/oracle/constraint.rs
- crates/core/src/oracle/multilinear.rs
- crates/core/src/polynomial/arith_circuit.rs
- crates/core/src/polynomial/multivariate.rs
- crates/core/src/protocols/evalcheck/tests.rs
- crates/core/src/protocols/gkr_exp/compositions.rs
- crates/core/src/protocols/sumcheck/oracles.rs
- crates/core/src/protocols/sumcheck/prove/eq_ind.rs
- crates/core/src/protocols/sumcheck/prove/oracles.rs
- crates/core/src/protocols/sumcheck/prove/regular_sumcheck.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/witness.rs
- crates/macros/src/arith_circuit_poly.rs
- crates/math/Cargo.toml
- crates/math/src/arith_expr.rs
- crates/utils/src/serialization.rs
Several changes to support sub-expression deduplication in `ExprTree` and ArithCircuitPoly:
1. Use `Arc` in `ArithExpr`
2. Introduce `ArithCircuit` as an intermediate object during `ArithExpr` serialization/deserialization of `ArithExpr` to preserve the `Arc`s keep pointing the same nodes after serialization roundtrip. This structure is not public.
3. At the moment of creation `ArithCircuitPoly` automatically deduplicates the nodes, reusing already created steps if possible. This seems to be of almost the same code complexity, so IMO there is no reason to introduce a new public entity `ArithExpr`.
> Common expression extraction in `ArithExpr`

- crates/compute/src/alloc.rs
- crates/compute/src/layer.rs
Accelerated compute backends will provide custom implementations for host and device allocations. Define a trait for bump allocators that will be used throughout Binius for compute buffer allocations.
> SYS-110:: define ComputeAllocator trait

- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/gkr_gpa/verify.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/lookup.rs
update `evalcheck` and `gkr_gpa` to correctly handle the case where n_vars = 0
> [M3] fix One element tables

- crates/core/src/polynomial/multivariate.rs
- crates/m3/Cargo.toml
- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/error.rs
- crates/m3/src/builder/mod.rs
- crates/m3/src/builder/structured.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
- crates/m3/src/gadgets/mod.rs
- crates/m3/src/gadgets/structured.rs
- crates/math/src/arith_expr.rs
This adds dynamically-sized structured columns. In a future change, I will add fixed-size structured columns as well.
The first structured column type is incremented value columns. These will be used for zCray address spaces.
> [m3] Add structured column type

- crates/core/benches/poly_commit.rs
- crates/core/src/constraint_system/error.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/piop/error.rs
- crates/core/src/piop/prove.rs
- crates/core/src/piop/tests.rs
- crates/core/src/piop/verify.rs
- crates/core/src/protocols/fri/common.rs
- crates/core/src/protocols/fri/error.rs
- crates/core/src/protocols/fri/prove.rs
- crates/core/src/protocols/fri/tests.rs
- crates/core/src/protocols/fri/verify.rs
- crates/core/src/reed_solomon/error.rs
- crates/core/src/reed_solomon/mod.rs
- crates/core/src/reed_solomon/reed_solomon.rs
- crates/core/src/ring_switch/tests.rs
- crates/math/src/binary_subspace.rs
- crates/ntt/src/single_threaded.rs
Previously, `ReedSolomonCode` owned an `impl AdditiveNTT` so that it could perform encoding. Several issues became apparent with that coupling:
- As we wrote FRI code, there became a clear need for `ReedSolomonCode`s that are not responsible for encoding, which could be used in the verifier.
- The NTT instance can be expensive to set up if precomputing twiddles, so it should be done outside of proving. See https://github.com/IrreducibleOSS/binius/issues/52. This does not fix the the issue but makes progress towards it.
- A planned feature is batched FRI proximity testing over separately committed interleaved codewords. When these codewords are different sizes, they must be committed over FRI-compatible domains. This decoupling is a step towards that.
> [reed_solomon] Extract NTT from ReedSolomonCode

- crates/m3/src/builder/constraint_system.rs
Instead of unconditionally adding the whole list of per partition oracle ids
into the constraint set, we check which ones are actually getting used.
See [CRY-296]
Fixes https://github.com/IrreducibleOSS/binius/issues/265
[CRY-296]: https://linear.app/irreducible/issue/CRY-297/optimize-m3-constraintset-compilation
> [m3] use only referenced oracle ids for zero check

- crates/core/src/protocols/evalcheck/evalcheck.rs
- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/tests.rs
- crates/core/src/protocols/evalcheck/verify.rs
- crates/core/src/protocols/greedy_evalcheck/prove.rs
- crates/core/src/protocols/greedy_evalcheck/verify.rs
This removes most of the serialization/deserialization & proof struct pattern matching logic from evalcheck. This simplifies the code a lot. Documentation needs updating.
> [evalcheck] Write duplicate claim advice directly to transcript

- crates/m3/src/gadgets/hash/keccak/mod.rs
Based on top of https://github.com/IrreducibleOSS/binius/pull/283, don't merge until that is in.
Turns out we don't run doc tests.
> [m3] fix rustdoc for the keccak module

- crates/m3/src/builder/table.rs
Based on top of https://github.com/IrreducibleOSS/binius/pull/285, don't merge until that is in.
This is important because otherwise instantiations of the same gadget will have all the constraints having the same name.
> [m3] namespace zero constraints

- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/evalcheck/verify.rs
- crates/core/src/ring_switch/prove.rs
They are different and should be handled differently. Composite MLE evaluations are not bivariate, and they don't use projection. In the future, we shouldn't handle them as regular sumchecks, we should prove them as MLEchecks, which have a more efficient proving algorithm.
> [evalcheck] Handle composite MLEs separately from projected bivariate sumchecks

- crates/m3/src/emulate.rs
Channel prior to this PR is overconstrained. It requires T to implement Default all the while the Channel does not actually contain any T by default.
> [m3] emulate Channel relax Default constraint

- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/greedy_evalcheck/mod.rs
- crates/core/src/protocols/greedy_evalcheck/prove.rs
- crates/core/src/protocols/greedy_evalcheck/tests.rs
The verifier processes claims successively, while the prover processes all projected claims first, followed by all composite.
As a result, if a projected and a composite claim have the same n_vars, the order of sumcheck_claims will differ between the verifier and prover.
The fix is a bit ad hoc, but #291 will provide a cleaner long-term solution
> [Fix] Match the order of processing bivariate sumcheck claims in evalcheck

- crates/core/src/constraint_system/prove.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/reed_solomon/error.rs
- crates/core/src/reed_solomon/reed_solomon.rs
- crates/ntt/benches/additive_ntt.rs
- crates/ntt/benches/large_transform.rs
- crates/ntt/src/additive_ntt.rs
- crates/ntt/src/dynamic_dispatch.rs
- crates/ntt/src/error.rs
- crates/ntt/src/multithreaded.rs
- crates/ntt/src/odd_interpolate.rs
- crates/ntt/src/single_threaded.rs
- crates/ntt/src/tests/ntt_tests.rs
- crates/ntt/src/tests/reference.rs
This generalizes the AdditiveNTT operation to be able to perform a truncated NTT, which skips rounds at the beginning of a forward transform and the end of an inverse transform. This is useful for Reed-Solomon encoding, where we want to run a large NTT but know apriori that the first few rounds have the effect of simply copying data.
This resolves a limitation of `ReedSolomonCode::encode`, which imposes a packing length restriction on the encoded message and also complicates the multithreading around the NTT with an additional Rayon loop. Now the multithreading is delegated to the AdditiveNTT implementation, which can size the matrix more appropriately.
> [ntt] Add skip_rounds parameter to AdditiveNTT

- crates/m3/src/emulate.rs
- crates/m3/tests/collatz.rs
- crates/m3/tests/fibonacci.rs
This allows to actually print what values are unbalanced which could aid
debugging.
> [m3] emulate::Channel::assert_balanced

- crates/core/src/protocols/evalcheck/evalcheck.rs
- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/verify.rs
The recursive verifier works with words, not bytes or usize.
Currently evalcheck proofs are encoded using bytes and usize. Either we
- switch binius to encoding using words
- post-process binius proofs to convert from bytes and usize to words.
I propose the former, and this is the PR. The latter seems unnecessarily complex.
> Serialize evalcheck proofs using u32s instead of bytes and usize

- crates/m3/src/builder/witness.rs
This PR aims at fixing the `eval_expr` method. It also adds a unit test with columns with different numbers of elements per row.
> Fix eval_expr

- crates/core/src/protocols/fri/logging.rs
- crates/core/src/protocols/fri/prove.rs
The hardware-accelerated fri_fold implementation's architecture depends on the relationship between the typical number of challenges and data length. Track the number of challenges per commitment round.
Sample output:
```
cargo run --example keccak
...
│  └── [step] FRI Fold Rounds [ 1.08s | 2.82% ] { phase = piop_compiler, round = 3, perfetto_category = phase.sub, dimensions_data = {"round":3,"log_batch_size":4,"codeword_len":524288} }
│     ├>incremental_proof_size: 32
│     ├── [task] FRI Fold [ 864.31ms | 2.27% ] { phase = piop_compiler, perfetto_category = task.main, dimensions_data = {"log_len":15,"log_batch_size":4,"num_challenges":4} }
│     │  └── fold_interleaved [ 864.28ms | 2.27% ]
│     └── [...] [ 212.51ms | 0.56% ]
```
SYS-210
> [core] FRI fold include num_challenges in dimensions trace

- Cargo.toml
- crates/core/src/piop/verify.rs
significantly improve FRI early termination calculation; this will lead to smaller proof sizes.
here, i am going to show that we can always improve our lives by advancing early termination _at least_ to the point at which the terminal codeword's log length becomes at least as large as the Merkle cap height. Equivalently, we want all Merkle paths to have nonnegative lengths, as opposed to "negative" ones—we don't want to commit to an oracle whose Merkle tree height is so short that the cap becomes "smaller than we decided we wanted". in one word, after this PR, [this min](https://github.com/IrreducibleOSS/binius/blob/ed227dfc69aff8eba37ec6da6edaf85189ec9e95/crates/core/src/merkle_tree/scheme.rs#L50) will have no effect (it will be a no-op).
terminating even earlier might help even more, …
> improve early FRI termination optimization

- crates/core/src/piop/prove.rs
- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/fri/logging.rs
- crates/core/src/protocols/fri/prove.rs
- crates/core/src/protocols/greedy_evalcheck/prove.rs
- crates/core/src/protocols/sumcheck/prove/batch_zerocheck.rs
- crates/core/src/protocols/sumcheck/prove/front_loaded.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/ring_switch/prove.rs
Log the tower levels of the codeword and NTT coefficients.
Also apply the proposal by @nikurt to pass the parameters to the span macro in a more elegant way.
> Add FRI folding tower level logging

- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
Small refactor and docs update to avoid confusion.
Why I didn't just inline it? Well then there won't be a platform for the
documentation.
> [m3] log_capacity does not depend on &self

- crates/core/src/constraint_system/exp.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/constraint_system/verify.rs
Descending claim order was disrupted when dynamic claims began being processed after static ones — this PR restores the correct order.
> [Fix] gkr_exp claims descending order

- crates/circuits/src/arithmetic/mul.rs
- crates/circuits/src/builder/constraint_system.rs
- crates/circuits/src/builder/witness.rs
- crates/circuits/src/lasso/big_integer_ops/byte_sliced_double_conditional_increment.rs
- crates/circuits/src/lasso/big_integer_ops/byte_sliced_modular_mul.rs
- crates/circuits/src/lasso/big_integer_ops/byte_sliced_test_utils.rs
- crates/circuits/src/lasso/sha256.rs
- crates/circuits/src/lib.rs
- crates/circuits/src/sha256.rs
- crates/core/src/constraint_system/channel.rs
- crates/core/src/constraint_system/prove.rs
- crates/core/src/constraint_system/validate.rs
- crates/core/src/oracle/constraint.rs
- crates/core/src/oracle/mod.rs
- crates/core/src/oracle/multilinear.rs
- crates/core/src/oracle/oracle_id.rs
- crates/core/src/piop/commit.rs
- crates/core/src/piop/prove.rs
- crates/core/src/protocols/evalcheck/evalcheck.rs
- crates/core/src/ring_switch/common.rs
- crates/core/src/ring_switch/tests.rs
- crates/core/src/witness.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/witness.rs
- crates/utils/src/graph.rs
OracleId becomes a newtype. This is a non-functional change.
As you see, this PR introduces some friction when using OracleId as an index by
forcing using `OracleId::from_index` and `OracleId::index`. This is intentional.
Users who call either of those functions should think of a better way of
structuring the code to avoid this. Some of the usages are hopefully going away
with follow-up refactorings.
As a bonus: turns out there were quite a bit of clones of MultilinearPolyOracle
struct. Each one is, if instantiated with e.g. F=BinaryField32b is 160 bytes.
Not too much but definitely annoying, especially considering why it was
happening. In one instance the whole clone of the structure would be done
just to get the name/label.
The tests seem to pass locally and petravm also green.
> [core] newtype OracleId

- .github/workflows/ci.yml
The graphite docs recommend this change to the github action `on` spec:
https://graphite.dev/docs/github-configuration-guidelines#github-actions
This is because PRs are stacked and you want to run CI tests on all PRs
in the stack, not just those that are based on the main.
The `edited` type is excluded here because this event is triggered when
Graphite makes changes to PR metadata and we don't want this to trigger
a CI run.
> Update github CI pull_request types to support graphite

- crates/compute/src/cpu/layer.rs
- crates/compute/src/layer.rs
Added a fold_right operation to the HAL and tied it to a low-performance CPU implementation for testing. Also switched the naming conventions of rows/columns in the left folding implementations to stay consistent with the way those operations are conventionally done.
> Fold right HAL operation

- .github/workflows/ci.yml
- crates/core/src/protocols/evalcheck/error.rs
- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/subclaims.rs
- crates/core/src/protocols/evalcheck/verify.rs
- crates/core/src/protocols/greedy_evalcheck/error.rs
- crates/core/src/protocols/greedy_evalcheck/prove.rs
- crates/core/src/protocols/greedy_evalcheck/verify.rs
- crates/core/src/protocols/sumcheck/oracles.rs
- crates/core/src/protocols/sumcheck/prove/oracles.rs
This PR collects CompositeMLE constraints separately by eval_point and builds an EqIndSumcheckProver instead of a RegularSumcheckProver.
This allows us to avoid repeated evaluations of eq_ind and is generally more efficient.
Also, to avoid searching for the position by eval_point, the prover provides it as an advice to the verifier.
> Reduce CompositeMLE evaluations to MLEchecks

- crates/m3/src/gadgets/hash/keccak/mod.rs
- crates/m3/src/gadgets/hash/keccak/trace.rs
- examples/keccak.rs
Updated the keccak gadget to:
1. Expose the input and output columns to the gadget.
2. Change the interface for the constructor and populate methods.
> [m3] Exposed input and output columns for Keccak-f[1600] gadget.

- crates/compute/src/cpu/layer.rs
The fold interleaved step is invariant to the selected batch size. Refactor the reference CPU implementation to make this property clear. Hardware implementations will benefit from the ability to select different batch sizes based on the properties of the target device.
> [compute] Simplify reference fri_fold operation

- crates/m3/src/gadgets/sub.rs
Closes [CRY-347].
[CRY-347]: https://linear.app/irreducible/issue/CRY-347/m3-u32sub-gadgets-doesnt-constrain-borrow-out
> [m3] fix underconstraining bug

- crates/core/src/constraint_system/prove.rs
- crates/core/src/constraint_system/verify.rs
Changed the evaluation order in grand product argument from `LowToHigh` to `HighToLow`.
Modified the evaluation order parameter in both the proving and verification functions from `EvaluationOrder::LowToHigh` to `EvaluationOrder::HighToLow` in the grand product argument batch operations. This change affects:
- `batch_prove` in `prove.rs`
- `batch_verify` in `verify.rs`
Run the existing test suite to ensure that proofs are still generated and verified correctly with the new evaluation order:
```
cargo test
```
The `HighToLow` evaluation order likely provides better performance characteristics or improved security properties for the grand product argument. This change ensures consistent evaluation order between proving and verification steps, which is critical for the cryptographic protocol …
> gpa-high-to-low

- examples/groestl.rs
- examples/u32_mul_gkr.rs
- examples/u64_mul.rs
This will speed up witness generation for examples in multithreaded configurations.
> [examples] Use fill_table_parallel instead of sequential

- crates/m3/src/emulate.rs
What this does is it improves the experience when running without RUST_BACKTRACE
=1.
Specifically, if we changed the collatz example to pull 2 instead of 1, we
would get the panic message below. Note the source of panic, it points to the
collatz code rather than the Channel code.
thread 'model::test_collatz_high_level_validation' panicked at crates/m3/tests/collatz.rs:53:27:
Channel is not balanced:
Unbalanced pushes:
1: 1
Unbalanced pulls:
1: 2
> [m3] slap track_caller on assert_balanced

- crates/utils/src/lib.rs
- crates/utils/src/mem.rs
As per @GraDKh request in this [comment].
I did not use the suggested identifier as, unlike in `assume_init`, we don't
really assume anything here, we are just converting a definitely inited slice
into a maybe uninited slice. Also to make it inline with the follow-up I
decided to call it `slice_uninit_mut` (put slice in the front).
[comment]: https://app.graphite.dev/github/pr/IrreducibleOSS/binius/353/%5Bcore%5D-miri
> [utils] introduce mem::slice_uninit_mut

- .pre-commit-config.yaml
Use cargo fmt instead of rustfmt for pre-commit hook
> [pre-commit] Fix rustfmt pre-commit hook

- crates/core/src/protocols/sumcheck/prove/univariate.rs
This make a step towards reusing the already-created NTT object in extrapolate_round_evals. We still can't actually use it because of extension field nonsense, but at least this ensures that the NTT domains are consistent.
> [zerocheck] Step towards reusing ntt

- crates/m3/src/builder/channel.rs
- crates/m3/src/builder/column.rs
- crates/m3/src/builder/constraint_system.rs
- crates/m3/src/builder/expr.rs
- crates/m3/src/builder/table.rs
- crates/m3/src/builder/witness.rs
This changeset aims to fix the implicit dependency of the witness on the order
of oracles added in `ConstraintSystem::compile`.. See [CRY-356] for more
details.
This does several things:
1. Prefers using ColumnId over indices
2. Introduction of `OracleLookup`
This starts using the ColumnId where possible. This change should really make
much less likely to confuse indices and improve general type-safety, and as well
as simplify the code a bit (one type is better than multiple). However, this
makes the column IDs to carry table_id around, but I don't think this is a
problem since the code is not hot.
Introduction the `OracleLookup` type. Prior this changeset
the data about which oracle came from which columns was lost. This type
is meant to store this information explicitly to be read by …
> [m3] don't assume oracle id order in witness

- crates/core/Cargo.toml
- crates/core/src/protocols/fri/tests.rs
- crates/core/src/protocols/sumcheck/prove/univariate.rs
- crates/core/src/reed_solomon/reed_solomon.rs
- crates/ntt/benches/additive_ntt.rs
- crates/ntt/benches/large_transform.rs
- crates/ntt/src/additive_ntt.rs
- crates/ntt/src/dynamic_dispatch.rs
- crates/ntt/src/error.rs
- crates/ntt/src/multithreaded.rs
- crates/ntt/src/odd_interpolate.rs
- crates/ntt/src/single_threaded.rs
- crates/ntt/src/tests/ntt_tests.rs
- crates/ntt/src/tests/reference.rs
- crates/utils/src/checked_arithmetics.rs
- examples/Cargo.toml
Modify the AdditiveNTT behavior so that the evaluation domains for differently-sized transforms are FRI-compatible. By FRI-compatible, we mean that encoding then FRI folding commutes with tensor folding then encoding. This is checked with a proptest in the `fri` module.
The interfaces for AdditiveNTT should be cleaned up to use structs with named fields and Default impls instead of many parameters. I'm leaving this for future work.
Fixes CRY-71
> [ntt] Add coset_bits parameter to AdditiveNTT

- crates/math/src/fold.rs
This condition was mistakenly left since the times this function was multithreaded.
This rolls back the slowdown that happened after https://github.com/IrreducibleOSS/binius/commit/57a4d56a4723c30683e384a8e35d1be5d68e1e84
> Remove outdated condition that prevented 1b optimization to happen

- crates/core/src/piop/tests.rs
- crates/core/src/piop/verify.rs
there is a very subtle issue in the current calculation of `fold_arities`; see the recent PR https://github.com/IrreducibleOSS/binius/pull/300.
the issue only arises in an essentially impossible-case---i.e., in which the `log_inv_rate` is strictly more than the `merkle_cap_height`, i.e., $\mathcal{R} > c$, where $c$ is the Merkle cap height. this will virtually never happen in real life, unless $\mathcal{R}$ is enormous---7 or 8 or so.
if this _were_ the case, then the current implementation can lead to a nonsensical scenario where sum(fold_arities) is > total_vars. this makes no sense, since we need to ship the terminal codeword before or equal to the point at which the message has become fully folded, and not after. in fact this gets caught in the current codebase, with a …
> fix calculation of fold arities. add larger test

- crates/m3/src/builder/column.rs
This essentially hides ColumnIndex and ColumnPartitionIndex from the outside
world.
> [m3] Add privacy to ColumnId and Col

- crates/compute/src/layer.rs
- crates/compute/src/lib.rs
- crates/core/Cargo.toml
- crates/core/src/composition/index.rs
- crates/core/src/protocols/sumcheck/mod.rs
- crates/core/src/protocols/sumcheck/v3/bivariate_product.rs
- crates/core/src/protocols/sumcheck/v3/error.rs
- crates/core/src/protocols/sumcheck/v3/mod.rs
- crates/field/src/tower.rs
This PR adds a new `v3` module to the sumcheck protocol implementation, which contains a specialized function for calculating round evaluations for bivariate product compositions. The implementation leverages the `binius_compute` crate for hardware acceleration.
Key changes:
- Add new `calculate_round_evals` function that computes batched evaluations of products of pairs of partially specialized multilinear polynomials
- Re-export `layer` and `memory` modules from the compute crate
- Add `binius_compute` dependency to the core crate
- Add getters for the `indices` field in `IndexComposition`
This is the first step toward a V3 sumcheck prover implementation that will eventually replace the current V2 prover.
> [CRY-364] Add bivariate_product round calculation function

- crates/m3/tests/merkle_tree.rs
This reverts commit 1240014c55ce66bdc0660e957a4e3794c5331a13.
Tests are failing on main.
> Revert "[m3] Binary merkle tree example internal nodes deduped.  (#386)"

- crates/core/src/protocols/evalcheck/prove.rs
- crates/core/src/protocols/evalcheck/tests.rs
- crates/core/src/protocols/evalcheck/verify.rs
There’s a case where a committed polynomial with n_vars = 0 and value [32] can be ZeroPadded into [32, 0, 0, 0], and the evaluation of this zero-padded polynomial may become 0.
As a result, when the verifier tries to derive:
inner_eval = eval * select_row_term.invert_or_zero()
for this committed polynomial, inner_eval ends up being 0, whereas it should be 32.
My hotfix for this case writes the original eval of the committed polynomial into the transcript and checks:
inner_eval * select_row_term == eval
So I believe this approach is secure.
> [Fix] evalcheck for ZeroPadded zero-variable polynomials

- crates/core/src/protocols/sumcheck/v3/bivariate_product.rs
The host allocator is no longer consumed, by the BivariateSumcheckProver on creation.
> BivariateProductSumcheck Borrows Host Allocator

- crates/compute/src/alloc.rs
- crates/compute/src/cpu/memory.rs
- crates/compute/src/memory.rs
- crates/fast_compute/src/memory.rs
Added ```remaining``` method to ComputeLayer allocators to create stack frames of ComputeLayer memory that are freed once the memory returned by ```remaining``` goes out of scope.
> Stacked Allocation Pattern for ComputeLayer memory

- crates/compute_test_utils/src/layer.rs
The prior version invoked `copy_h2d` with a host buffer that was not allocated with the host allocator. Using a buffer allocated with the default allocator results in incorrect behavior if the hardware implementation derives additional addressing information during copies from the provided slice assuming that the slice was allocated by the implementation's host allocator.
> SYS-258: fix `test_generic_fri_fold` host buffer

- crates/compute_test_utils/src/bivariate_sumcheck.rs
Allocate the host evaluations data using the HAL-specific host allocator. Doing so is required for compatibility with `host_alloc` across implementations.
> SYS-274: fix bivariate sumcheck host alloc

- crates/ntt/src/tests/reference.rs
In https://github.com/IrreducibleOSS/binius/pull/770 a new convention for the `AdditiveNTT::subspace(...)` function was introduced, but it was not adapted for the reference `SimpleAdditiveNTT` implementation. This PR fixes that.
> [ntt] Fix subspace convention for reference implementation

- crates/m3/Cargo.toml
- crates/m3/src/gadgets/hash/mod.rs
- crates/m3/src/gadgets/hash/sha256.rs
This PR adds a complete SHA-256 hash function gadget to the M3 framework. The implementation follows the FIPS 180-4 standard and includes:
- A full SHA-256 compression function implementation
- Message schedule computation with σ₀ and σ₁ functions
- Compression round implementation with Σ₀, Σ₁, Ch, and Maj functions
- Working variable state management across all 64 rounds
- Final state computation
The gadget is thoroughly tested against the standard SHA-256 implementation from the sha2 crate.
> [m3] Add SHA-256 hash gadget implementation
